#!/bin/bash
#PBS -l select=1:ncpus=24:mpiprocs=20
#PBS -P CBBI1106
#PBS -q test
#PBS -l walltime=00:08:00
#PBS -o /mnt/lustre/users/blombard/analysis/oe_files/std_m4.out
#PBS -e /mnt/lustre/users/blombard/analysis/oe_files/std_m4.err
#PBS -N m4_analysis
#PBS -M belindalombard@sun.ac.za
#PBS -m be



# Add R module (includes appropriate openMPI and gcc modules)
module add chpc/R/3.5.1-gcc7.2.0

# explicitly calculate number of processes.
nproc=`cat $PBS_NODEFILE | wc -l`

# make sure we're in the correct working directory.
cd /mnt/lustre/users/blombard/analysis/

mkdir oe_files

mpirun -np $nproc -machinefile $PBS_NODEFILE  R --slave -f method_4_analysis/method_4_analysis_CHPC.R --args 901 910 10